import { Drawer } from "@/components/common/Drawer";
import { SeverityBadge } from "@/components/common/SeverityBadge";
import { StatusBadge, PriorityBadge } from "@/components/common/StatusBadge";
import { Timeline } from "@/components/common/Timeline";
import { formatDateTime } from "@/utils/format";
import type { Alert, IncidentTimelineEvent } from "@/types";

interface AlertDetailDrawerProps {
  alert: Alert | null;
  onClose: () => void;
}

// A lightweight timeline synthesized from the alert record itself — the full
// incident timeline lives on the Incidents page once an alert is escalated.
function alertTimeline(alert: Alert): IncidentTimelineEvent[] {
  return [
    { id: "e1", label: "Alert generated by detection engine", actor: "system", timestamp: alert.detectedAt },
    ...(alert.assignedAnalyst
      ? [
          {
            id: "e2",
            label: `Assigned to ${alert.assignedAnalyst.name}`,
            actor: "analyst" as const,
            timestamp: alert.updatedAt,
          },
        ]
      : []),
    { id: "e3", label: `Status updated to "${alert.status.replace("_", " ")}"`, actor: "analyst", timestamp: alert.updatedAt },
  ];
}

export function AlertDetailDrawer({ alert, onClose }: AlertDetailDrawerProps) {
  return (
    <Drawer open={!!alert} onClose={onClose} title={alert?.title ?? ""} subtitle={alert?.id}>
      {alert && (
        <div className="space-y-6">
          <div className="flex items-center gap-2 flex-wrap">
            <SeverityBadge severity={alert.severity} />
            <PriorityBadge priority={alert.priority} />
            <StatusBadge status={alert.status} />
          </div>

          <dl className="grid grid-cols-2 gap-x-4 gap-y-3 text-xs">
            <Field label="Risk Score" value={String(alert.riskScore)} />
            <Field label="Confidence" value={`${alert.confidenceScore}%`} />
            <Field label="Assigned Analyst" value={alert.assignedAnalyst?.name ?? "Unassigned"} />
            <Field label="Detected" value={formatDateTime(alert.detectedAt)} />
          </dl>

          <div>
            <p className="text-xs font-semibold text-ink-primary mb-3">Alert Timeline</p>
            <Timeline events={alertTimeline(alert)} />
          </div>
        </div>
      )}
    </Drawer>
  );
}

function Field({ label, value }: { label: string; value?: string }) {
  return (
    <div>
      <dt className="text-[10px] uppercase tracking-wide text-ink-tertiary">{label}</dt>
      <dd className="text-ink-primary mt-0.5">{value ?? "—"}</dd>
    </div>
  );
}
