import { useState } from "react";
import { Inbox } from "lucide-react";
import { PageHeader } from "@/components/common/PageHeader";
import { SearchBar } from "@/components/common/SearchBar";
import { FilterPanel } from "@/components/common/FilterPanel";
import { Pagination } from "@/components/common/Pagination";
import { EmptyState } from "@/components/common/EmptyState";
import { ErrorState } from "@/components/common/ErrorState";
import { CardSkeleton } from "@/components/common/Skeleton";
import { ThreatCard } from "@/components/alerts/ThreatCard";
import { ThreatDetailDrawer } from "@/components/alerts/ThreatDetailDrawer";
import { useAlerts } from "@/hooks/useAlerts";
import type { Alert, Severity } from "@/types";

const PAGE_SIZE = 9;

export default function ActiveThreatsPage() {
  const [search, setSearch] = useState("");
  const [severities, setSeverities] = useState<Severity[]>([]);
  const [page, setPage] = useState(1);
  const [selected, setSelected] = useState<Alert | null>(null);

  const { data, isLoading, isError, refetch, isPlaceholderData } = useAlerts({
    page,
    pageSize: PAGE_SIZE,
    search,
    severities: severities.length ? severities : undefined,
  });

  function toggleSeverity(s: Severity) {
    setPage(1);
    setSeverities((prev) => (prev.includes(s) ? prev.filter((x) => x !== s) : [...prev, s]));
  }

  return (
    <div className="space-y-5">
      <PageHeader
        title="Threat Monitor"
        description="Live threat feed generated by the anomaly detection and classification engine"
      />

      <div className="flex flex-col sm:flex-row gap-3 sm:items-center">
        <SearchBar
          value={search}
          onChange={(v) => {
            setSearch(v);
            setPage(1);
          }}
          placeholder="Search by threat, IP, asset, or CVE..."
        />
        <FilterPanel selectedSeverities={severities} onToggleSeverity={toggleSeverity} onClear={() => setSeverities([])} />
      </div>

      {isLoading && !data ? (
        <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">
          {Array.from({ length: 6 }).map((_, i) => <CardSkeleton key={i} />)}
        </div>
      ) : isError ? (
        <ErrorState onRetry={() => refetch()} />
      ) : !data || data.items.length === 0 ? (
        <EmptyState icon={Inbox} title="No threats match your filters" description="Try clearing the search or severity filters." />
      ) : (
        <div className={isPlaceholderData ? "opacity-60 transition-opacity" : "transition-opacity"}>
          <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">
            {data.items.map((alert, i) => (
              <ThreatCard key={alert.id} alert={alert} index={i} onClick={() => setSelected(alert)} />
            ))}
          </div>
          <Pagination page={page} pageSize={PAGE_SIZE} total={data.total} onPageChange={setPage} />
        </div>
      )}

      <ThreatDetailDrawer alert={selected} onClose={() => setSelected(null)} />
    </div>
  );
}
