import type {
  Alert,
  AlertPriority,
  AiInsight,
  AssetSummary,
  AttackTrendPoint,
  CountryThreatStat,
  Incident,
  IncidentStatus,
  IncidentTimelineEvent,
  NotificationItem,
  ReportSummary,
  ResponseRecommendation,
  Severity,
  SeverityDistribution,
  ThreatCategoryCount,
  ThreatMapPoint,
  TopAttackSource,
} from "@/types";
import {
  id,
  pick,
  pickWeighted,
  randInt,
  randomCveId,
  randomInternalIp,
  randomIp,
  randomPastTimestamp,
} from "./random";
import { ANALYSTS, ASSET_NAMES, THREAT_COUNTRIES, THREAT_TEMPLATES, mitreForTemplate } from "./referenceData";

const SEVERITY_WEIGHTS: Record<Severity, number> = {
  critical: 6,
  high: 16,
  medium: 34,
  low: 32,
  info: 12,
};

const STATUS_WEIGHTS: Record<IncidentStatus, number> = {
  open: 22,
  investigating: 28,
  contained: 15,
  resolved: 30,
  false_positive: 5,
};

const PRIORITY_BY_SEVERITY: Record<Severity, AlertPriority> = {
  critical: "p1",
  high: "p2",
  medium: "p3",
  low: "p4",
  info: "p4",
};

const DATA_SOURCES = [
  "cloud_audit_logs",
  "vpc_flow_logs",
  "security_command_center",
  "external_threat_intel",
] as const;

function buildAlert(n: number): Alert {
  const template = pick(THREAT_TEMPLATES);
  const severity = pickWeighted(SEVERITY_WEIGHTS);
  const mitre = mitreForTemplate(template);
  const detectedAt = randomPastTimestamp(24 * 14);
  const includeCve = ["Exploit", "Malware", "Web Attack"].includes(template.category) && randInt(0, 1) === 1;

  return {
    id: id("ALT", n),
    title: template.name,
    description: `${template.name} detected on ${pick(ASSET_NAMES).name}. Confidence and risk scoring generated by the anomaly detection and classification engine.`,
    severity,
    status: pickWeighted(STATUS_WEIGHTS),
    source: pick(DATA_SOURCES),
    mitreTactic: `${mitre.tacticName} (${mitre.tacticId})`,
    mitreTechniqueId: mitre.techniqueId,
    confidenceScore: randInt(58, 99),
    riskScore: randInt(10, 98),
    assetId: pick(ASSET_NAMES).name,
    sourceIp: randomIp(),
    destinationIp: randomInternalIp(),
    detectedAt,
    updatedAt: detectedAt,
    priority: PRIORITY_BY_SEVERITY[severity],
    assignedAnalyst: randInt(0, 3) > 0 ? pick(ANALYSTS) : undefined,
    cveId: includeCve ? randomCveId() : undefined,
    attackType: template.category,
  };
}

export const MOCK_ALERTS: Alert[] = Array.from({ length: 64 }, (_, i) => buildAlert(i + 1));

function buildIncidentTimeline(alert: Alert, status: IncidentStatus): IncidentTimelineEvent[] {
  const events: IncidentTimelineEvent[] = [
    {
      id: "evt-1",
      label: `Anomaly detected by ML engine (confidence ${alert.confidenceScore}%)`,
      actor: "system",
      timestamp: alert.detectedAt,
    },
    {
      id: "evt-2",
      label: "Incident auto-created and correlated with related alerts",
      actor: "system",
      timestamp: alert.detectedAt,
    },
  ];
  if (alert.assignedAnalyst) {
    events.push({
      id: "evt-3",
      label: `Assigned to ${alert.assignedAnalyst.name} for triage`,
      actor: "analyst",
      timestamp: alert.updatedAt,
    });
  }
  events.push({
    id: "evt-4",
    label: "Security Assistant suggested containment playbook based on MITRE ATT&CK mapping",
    actor: "ai_assistant",
    timestamp: alert.updatedAt,
    detail: `Recommended technique-specific response for ${alert.mitreTechniqueId}`,
  });
  if (status === "contained" || status === "resolved") {
    events.push({
      id: "evt-5",
      label: status === "resolved" ? "Incident marked resolved" : "Threat contained, monitoring for recurrence",
      actor: "analyst",
      timestamp: alert.updatedAt,
    });
  }
  return events;
}

function buildIncident(n: number, alert: Alert): Incident {
  const status = pickWeighted(STATUS_WEIGHTS);
  return {
    id: id("INC", n),
    alertIds: [alert.id],
    title: alert.title,
    severity: alert.severity,
    status,
    assignee: alert.assignedAnalyst?.name,
    riskScore: alert.riskScore,
    createdAt: alert.detectedAt,
    updatedAt: alert.updatedAt,
    timeline: buildIncidentTimeline(alert, status),
  };
}

export const MOCK_INCIDENTS: Incident[] = MOCK_ALERTS.filter((_, i) => i % 3 === 0).map((alert, i) =>
  buildIncident(i + 1, alert)
);

export const RESPONSE_RECOMMENDATIONS: Record<string, ResponseRecommendation[]> = Object.fromEntries(
  MOCK_INCIDENTS.map((inc) => [
    inc.id,
    [
      { id: "r1", action: "Isolate affected host from network segment", priority: "immediate" as const, automatable: true },
      { id: "r2", action: "Rotate credentials for associated service accounts", priority: "immediate" as const, automatable: true },
      { id: "r3", action: "Review VPC flow logs for lateral movement in the past 72h", priority: "high" as const, automatable: false },
      { id: "r4", action: "Notify asset owner and update incident severity if scope expands", priority: "recommended" as const, automatable: false },
    ],
  ])
);

// ---- Analytics ----

export const SEVERITY_DISTRIBUTION: SeverityDistribution[] = (
  ["critical", "high", "medium", "low", "info"] as Severity[]
).map((severity) => ({
  severity,
  count: MOCK_ALERTS.filter((a) => a.severity === severity).length,
}));

export const ATTACK_TREND: AttackTrendPoint[] = Array.from({ length: 30 }, (_, i) => {
  const date = new Date();
  date.setDate(date.getDate() - (29 - i));
  const base = 4 + Math.round(3 * Math.sin(i / 4));
  return {
    timestamp: date.toISOString().slice(0, 10),
    critical: Math.max(0, base - 3 + randInt(0, 2)),
    high: Math.max(0, base - 1 + randInt(0, 3)),
    medium: Math.max(0, base + 2 + randInt(0, 4)),
    low: Math.max(0, base + 4 + randInt(0, 5)),
  };
});

export const THREAT_CATEGORIES: ThreatCategoryCount[] = Object.entries(
  MOCK_ALERTS.reduce<Record<string, number>>((acc, a) => {
    acc[a.attackType] = (acc[a.attackType] ?? 0) + 1;
    return acc;
  }, {})
)
  .map(([category, count]) => ({ category, count }))
  .sort((a, b) => b.count - a.count);

export const TOP_ATTACK_SOURCES: TopAttackSource[] = Array.from({ length: 8 }, () => {
  const c = pick(THREAT_COUNTRIES);
  return {
    ip: randomIp(),
    country: c.country,
    attackCount: randInt(12, 340),
    riskScore: randInt(40, 99),
  };
}).sort((a, b) => b.attackCount - a.attackCount);

export const THREAT_MAP_POINTS: ThreatMapPoint[] = THREAT_COUNTRIES.map((c, i) => ({
  id: id("MAP", i + 1),
  lat: c.lat,
  lng: c.lng,
  country: c.country,
  severity: pickWeighted(SEVERITY_WEIGHTS),
  eventCount: randInt(8, 260),
}));

export const COUNTRY_THREAT_STATS: CountryThreatStat[] = THREAT_COUNTRIES.map((c) => ({
  country: c.country,
  countryCode: c.countryCode,
  lat: c.lat,
  lng: c.lng,
  threatCount: randInt(15, 310),
  severity: pickWeighted(SEVERITY_WEIGHTS),
})).sort((a, b) => b.threatCount - a.threatCount);

// ---- Assets ----

export const MOCK_ASSETS: AssetSummary[] = ASSET_NAMES.map((a, i) => ({
  id: id("AST", i + 1),
  name: a.name,
  type: a.type,
  riskScore: randInt(5, 95),
  criticality: pick(["critical", "high", "medium", "low"] as const),
}));

// ---- AI Insights ----

export const AI_INSIGHTS: AiInsight[] = [
  {
    id: "ins-1",
    title: "Credential stuffing spike from Eastern Europe IP ranges",
    summary:
      "18 correlated brute-force alerts in the last 6 hours share a source ASN. Recommend temporary rate-limiting on the auth-service-identity-pool endpoint.",
    severity: "high",
    relatedAlertId: MOCK_ALERTS[2]?.id,
    generatedAt: randomPastTimestamp(6),
  },
  {
    id: "ins-2",
    title: "Cryptomining pattern matches prior incident INC-00004",
    summary:
      "CPU/network signature on prod-k8s-cluster-us-east closely matches a contained incident from 11 days ago. Same C2 domain family observed.",
    severity: "critical",
    generatedAt: randomPastTimestamp(3),
  },
  {
    id: "ins-3",
    title: "IAM policy drift on 3 service accounts this week",
    summary:
      "Unusual grant of storage.admin to service accounts outside the standard provisioning workflow. Worth a manual access review.",
    severity: "medium",
    generatedAt: randomPastTimestamp(20),
  },
  {
    id: "ins-4",
    title: "DNS tunneling indicators trending down after containment",
    summary: "Beaconing volume dropped 74% following yesterday's egress filtering change on vpn-gateway-corp.",
    severity: "low",
    generatedAt: randomPastTimestamp(30),
  },
];

// ---- Notifications ----

export const MOCK_NOTIFICATIONS: NotificationItem[] = [
  { id: "nt-1", title: "Critical alert triggered", message: "Ransomware behavior pattern identified on billing-service-vm-03", severity: "critical", read: false, createdAt: randomPastTimestamp(1) },
  { id: "nt-2", title: "Incident assigned to you", message: "INC-00007 — Lateral Movement via SMB Share", severity: "high", read: false, createdAt: randomPastTimestamp(4) },
  { id: "nt-3", title: "Weekly digest ready", message: "Your weekly security report is ready to view", severity: "info", read: true, createdAt: randomPastTimestamp(20) },
  { id: "nt-4", title: "Asset risk score increased", message: "customer-data-bucket risk score rose from 41 to 68", severity: "medium", read: true, createdAt: randomPastTimestamp(28) },
];

// ---- Reports ----

export const MOCK_REPORTS: ReportSummary[] = [
  {
    id: "rep-w-1",
    title: "Weekly Security Summary",
    period: "weekly",
    dateRange: "Jul 7 – Jul 13, 2026",
    generatedAt: randomPastTimestamp(48),
    highlights: [
      "3 critical incidents contained within SLA (avg 42 min to containment)",
      "Credential stuffing attempts up 22% week-over-week",
      "No confirmed data exfiltration events",
    ],
    metrics: {
      totalThreats: 214,
      totalThreatsDelta: 12,
      activeAlerts: 37,
      activeAlertsDelta: -4,
      riskScore: 58,
      riskScoreDelta: -3,
      assetsMonitored: 128,
      assetsMonitoredDelta: 2,
    },
  },
  {
    id: "rep-m-1",
    title: "Monthly Security Summary",
    period: "monthly",
    dateRange: "June 2026",
    generatedAt: randomPastTimestamp(72),
    highlights: [
      "Overall risk score improved from 64 to 58",
      "MITRE technique T1110 (Brute Force) remains top detection category",
      "2 zero-day exploit attempts blocked at the edge",
    ],
    metrics: {
      totalThreats: 891,
      totalThreatsDelta: -6,
      activeAlerts: 37,
      activeAlertsDelta: -4,
      riskScore: 58,
      riskScoreDelta: -6,
      assetsMonitored: 128,
      assetsMonitoredDelta: 5,
    },
  },
];

// ---- Overview metrics ----

export function computeOverviewMetrics() {
  return {
    totalThreats: MOCK_ALERTS.length + randInt(140, 180),
    totalThreatsDelta: 8,
    activeAlerts: MOCK_ALERTS.filter((a) => a.status === "open" || a.status === "investigating").length,
    activeAlertsDelta: -5,
    riskScore: 58,
    riskScoreDelta: -3,
    assetsMonitored: MOCK_ASSETS.length + randInt(90, 120),
    assetsMonitoredDelta: 2,
  };
}

// ---- AI chat ----

export const SUGGESTED_QUESTIONS = [
  "Summarize today's critical alerts",
  "What's the MITRE mapping for INC-00001?",
  "Recommend containment steps for brute-force attacks",
  "Which assets have the highest risk score right now?",
  "Explain the DNS tunneling detection on vpn-gateway-corp",
];
