from __future__ import annotations

import random
from datetime import datetime, timedelta, UTC

from sqlalchemy.orm import Session

from app.models.alert import Alert, Analyst
from app.models.asset import Asset
from app.models.incident import Incident
from app.models.insight import AiInsight
from app.models.notification import Notification
from app.models.report import Report
from app.models.settings import AppSettings
from app.models.threatmap import CountryStat, ThreatMapPoint
from app.ml import confidence_scoring, risk_scoring
from app.seed.reference_data import (
    ANALYSTS,
    ASSET_NAMES,
    DATA_SOURCES,
    PRIORITY_BY_SEVERITY,
    SEVERITY_WEIGHTS,
    STATUS_WEIGHTS,
    THREAT_COUNTRIES,
    THREAT_TEMPLATES,
)

_rng = random.Random(1337)


def _weighted_choice(weights: dict[str, int]) -> str:
    keys = list(weights.keys())
    values = list(weights.values())
    return _rng.choices(keys, weights=values, k=1)[0]


def _random_ip() -> str:
    return f"{_rng.randint(1, 223)}.{_rng.randint(0, 255)}.{_rng.randint(0, 255)}.{_rng.randint(1, 254)}"


def _random_internal_ip() -> str:
    return f"10.{_rng.randint(0, 4)}.{_rng.randint(0, 255)}.{_rng.randint(1, 254)}"


def _random_cve() -> str:
    year = _rng.choice(["2023", "2024", "2025", "2026"])
    return f"CVE-{year}-{_rng.randint(1000, 49999)}"


def _past_timestamp(max_hours_ago: int) -> datetime:
    delta = timedelta(hours=_rng.randint(1, max_hours_ago), minutes=_rng.randint(0, 59))
    return datetime.now(UTC).replace(tzinfo=None) - delta


def is_seeded(db: Session) -> bool:
    return db.query(Alert).first() is not None


def seed_database(db: Session) -> None:
    if is_seeded(db):
        return

    # ---- Analysts ----
    analysts = [Analyst(id=a["id"], name=a["name"], initials=a["initials"]) for a in ANALYSTS]
    db.add_all(analysts)
    db.flush()

    # ---- Alerts ----
    alerts: list[Alert] = []
    for i in range(1, 65):
        template = _rng.choice(THREAT_TEMPLATES)
        severity = _weighted_choice(SEVERITY_WEIGHTS)
        detected_at = _past_timestamp(24 * 14)
        include_cve = template["category"] in ("Exploit", "Malware", "Web Attack") and _rng.randint(0, 1) == 1
        analyst = _rng.choice(analysts) if _rng.randint(0, 3) > 0 else None
        asset = _rng.choice(ASSET_NAMES)

        # Confidence and risk scores come from the ML placeholder modules
        # (app/ml/confidence_scoring.py, app/ml/risk_scoring.py) rather than
        # a bare randint — this is the actual call path a real event
        # ingestion pipeline would use; swapping the placeholder internals
        # for trained models later requires no change here.
        alert_id = f"ALT-{i:05d}"
        asset_criticality = "critical" if asset["type"] in ("database", "identity") else "medium"

        alert = Alert(
            id=alert_id,
            title=template["name"],
            description=(
                f"{template['name']} detected on {asset['name']}. Confidence and risk scoring "
                "generated by the anomaly detection and classification engine."
            ),
            severity=severity,
            status=_weighted_choice(STATUS_WEIGHTS),
            source=_rng.choice(DATA_SOURCES),
            mitre_tactic=f"{template['tactic_name']} ({template['tactic_id']})",
            mitre_technique_id=template["technique_id"],
            confidence_score=confidence_scoring.compute_confidence(alert_id),
            risk_score=risk_scoring.compute_risk_score(severity, asset_criticality, jitter_seed=alert_id),
            asset_id=asset["name"],
            source_ip=_random_ip(),
            destination_ip=_random_internal_ip(),
            detected_at=detected_at,
            updated_at=detected_at,
            priority=PRIORITY_BY_SEVERITY[severity],
            cve_id=_random_cve() if include_cve else None,
            attack_type=template["category"],
            assigned_analyst_id=analyst.id if analyst else None,
        )
        alerts.append(alert)

    db.add_all(alerts)
    db.flush()

    # ---- Incidents (derived from every 3rd alert, mirrors mockData.ts) ----
    incidents: list[Incident] = []
    for i, alert in enumerate([a for idx, a in enumerate(alerts) if idx % 3 == 0], start=1):
        status = _weighted_choice(STATUS_WEIGHTS)
        template = next((t for t in THREAT_TEMPLATES if t["name"] == alert.title), THREAT_TEMPLATES[0])

        timeline = [
            {
                "id": "evt-1",
                "label": f"Anomaly detected by ML engine (confidence {alert.confidence_score}%)",
                "actor": "system",
                "timestamp": alert.detected_at.isoformat(),
            },
            {
                "id": "evt-2",
                "label": "Incident auto-created and correlated with related alerts",
                "actor": "system",
                "timestamp": alert.detected_at.isoformat(),
            },
        ]
        if alert.assigned_analyst_id:
            analyst = next(a for a in analysts if a.id == alert.assigned_analyst_id)
            timeline.append(
                {
                    "id": "evt-3",
                    "label": f"Assigned to {analyst.name} for triage",
                    "actor": "analyst",
                    "timestamp": alert.updated_at.isoformat(),
                }
            )
        timeline.append(
            {
                "id": "evt-4",
                "label": "Security Assistant suggested containment playbook based on MITRE ATT&CK mapping",
                "actor": "ai_assistant",
                "timestamp": alert.updated_at.isoformat(),
                "detail": f"Recommended technique-specific response for {alert.mitre_technique_id}",
            }
        )
        if status in ("contained", "resolved"):
            timeline.append(
                {
                    "id": "evt-5",
                    "label": "Incident marked resolved" if status == "resolved" else "Threat contained, monitoring for recurrence",
                    "actor": "analyst",
                    "timestamp": alert.updated_at.isoformat(),
                }
            )

        recommendations = [
            {"id": "r1", "action": "Isolate affected host from network segment", "priority": "immediate", "automatable": True},
            {"id": "r2", "action": "Rotate credentials for associated service accounts", "priority": "immediate", "automatable": True},
            {"id": "r3", "action": "Review VPC flow logs for lateral movement in the past 72h", "priority": "high", "automatable": False},
            {"id": "r4", "action": "Notify asset owner and update incident severity if scope expands", "priority": "recommended", "automatable": False},
        ]

        incidents.append(
            Incident(
                id=f"INC-{i:05d}",
                alert_ids=[alert.id],
                title=alert.title,
                severity=alert.severity,
                status=status,
                assignee=next((a.name for a in analysts if a.id == alert.assigned_analyst_id), None),
                risk_score=alert.risk_score,
                created_at=alert.detected_at,
                updated_at=alert.updated_at,
                timeline=timeline,
                mitre_tactic_id=template["tactic_id"],
                mitre_tactic_name=template["tactic_name"],
                mitre_technique_id=template["technique_id"],
                mitre_technique_name=template["technique_name"],
                response_recommendations=recommendations,
            )
        )
    db.add_all(incidents)

    # ---- Assets ----
    assets = [
        Asset(
            id=f"AST-{i:05d}",
            name=a["name"],
            type=a["type"],
            risk_score=_rng.randint(5, 95),
            criticality=_rng.choice(["critical", "high", "medium", "low"]),
        )
        for i, a in enumerate(ASSET_NAMES, start=1)
    ]
    db.add_all(assets)

    # ---- Threat map points + country stats ----
    map_points = [
        ThreatMapPoint(
            id=f"MAP-{i:05d}",
            lat=c["lat"],
            lng=c["lng"],
            country=c["country"],
            severity=_weighted_choice(SEVERITY_WEIGHTS),
            event_count=_rng.randint(8, 260),
        )
        for i, c in enumerate(THREAT_COUNTRIES, start=1)
    ]
    db.add_all(map_points)

    country_stats = [
        CountryStat(
            country_code=c["country_code"],
            country=c["country"],
            lat=c["lat"],
            lng=c["lng"],
            threat_count=_rng.randint(15, 310),
            severity=_weighted_choice(SEVERITY_WEIGHTS),
        )
        for c in THREAT_COUNTRIES
    ]
    db.add_all(country_stats)

    # ---- AI insights ----
    insights = [
        AiInsight(
            id="ins-1",
            title="Credential stuffing spike from Eastern Europe IP ranges",
            summary=(
                "18 correlated brute-force alerts in the last 6 hours share a source ASN. "
                "Recommend temporary rate-limiting on the auth-service-identity-pool endpoint."
            ),
            severity="high",
            related_alert_id=alerts[2].id if len(alerts) > 2 else None,
            generated_at=_past_timestamp(6),
        ),
        AiInsight(
            id="ins-2",
            title="Cryptomining pattern matches prior incident INC-00004",
            summary=(
                "CPU/network signature on prod-k8s-cluster-us-east closely matches a contained "
                "incident from 11 days ago. Same C2 domain family observed."
            ),
            severity="critical",
            generated_at=_past_timestamp(3),
        ),
        AiInsight(
            id="ins-3",
            title="IAM policy drift on 3 service accounts this week",
            summary=(
                "Unusual grant of storage.admin to service accounts outside the standard "
                "provisioning workflow. Worth a manual access review."
            ),
            severity="medium",
            generated_at=_past_timestamp(20),
        ),
        AiInsight(
            id="ins-4",
            title="DNS tunneling indicators trending down after containment",
            summary="Beaconing volume dropped 74% following yesterday's egress filtering change on vpn-gateway-corp.",
            severity="low",
            generated_at=_past_timestamp(30),
        ),
    ]
    db.add_all(insights)

    # ---- Notifications ----
    notifications = [
        Notification(id="nt-1", title="Critical alert triggered", message="Ransomware behavior pattern identified on billing-service-vm-03", severity="critical", read=False, created_at=_past_timestamp(1)),
        Notification(id="nt-2", title="Incident assigned to you", message="INC-00007 — Lateral Movement via SMB Share", severity="high", read=False, created_at=_past_timestamp(4)),
        Notification(id="nt-3", title="Weekly digest ready", message="Your weekly security report is ready to view", severity="info", read=True, created_at=_past_timestamp(20)),
        Notification(id="nt-4", title="Asset risk score increased", message="customer-data-bucket risk score rose from 41 to 68", severity="medium", read=True, created_at=_past_timestamp(28)),
    ]
    db.add_all(notifications)

    # ---- Reports ----
    base_metrics = {
        "totalThreats": 214, "totalThreatsDelta": 12, "activeAlerts": 37, "activeAlertsDelta": -4,
        "riskScore": 58, "riskScoreDelta": -3, "assetsMonitored": 128, "assetsMonitoredDelta": 2,
    }
    monthly_metrics = {
        "totalThreats": 891, "totalThreatsDelta": -6, "activeAlerts": 37, "activeAlertsDelta": -4,
        "riskScore": 58, "riskScoreDelta": -6, "assetsMonitored": 128, "assetsMonitoredDelta": 5,
    }
    reports = [
        Report(
            id="rep-w-1", title="Weekly Security Summary", period="weekly", date_range="Jul 7 – Jul 13, 2026",
            generated_at=_past_timestamp(48),
            highlights=[
                "3 critical incidents contained within SLA (avg 42 min to containment)",
                "Credential stuffing attempts up 22% week-over-week",
                "No confirmed data exfiltration events",
            ],
            metrics=base_metrics,
        ),
        Report(
            id="rep-m-1", title="Monthly Security Summary", period="monthly", date_range="June 2026",
            generated_at=_past_timestamp(72),
            highlights=[
                "Overall risk score improved from 64 to 58",
                "MITRE technique T1110 (Brute Force) remains top detection category",
                "2 zero-day exploit attempts blocked at the edge",
            ],
            metrics=monthly_metrics,
        ),
    ]
    db.add_all(reports)

    # ---- Default settings row ----
    db.add(
        AppSettings(
            id=1,
            theme="dark",
            dense_tables=False,
            auto_refresh_interval=30,
            notifications={
                "criticalAlerts": True,
                "weeklyDigest": True,
                "incidentAssigned": True,
                "aiInsights": False,
            },
            dashboard={
                "defaultLandingPage": "/",
                "showAiInsights": True,
                "compactCards": False,
            },
        )
    )

    db.commit()
